- name: bootstrap app server
  hosts: web
  become: yes
  vars:
    redis_password: 'Redis2025'
    minio_user: 'admin'
    minio_password: 'AdminMinio2025'
  tasks:
    - name: Install Docker
      ansible.builtin.include_tasks: tasks/docker.yml

    - name: Include redis tasks
      ansible.builtin.include_tasks: tasks/redis.yml
      when: redis_password is defined

    - name: Include minio tasks
      ansible.builtin.include_tasks: tasks/minio.yml
      when: minio_user is defined and minio_password is defined

    - name: Include jenkins tasks
      ansible.builtin.include_tasks: tasks/jenkins.yml

    - name: Include portainer tasks
      ansible.builtin.include_tasks: tasks/portainer.yml

    - name: Include kafka tasks
      ansible.builtin.include_tasks: tasks/kafka.yml

    - name: Include jaeger tasks
      ansible.builtin.include_tasks: tasks/jaeger.yml

